name: vsdpy310
channels:
  - defaults
dependencies:
  - python=3.10
  - tensorflow==2.12
  - pandas==2.2.2
  - numpy==1.23.5
  - matplotlib==3.9.2
  - scipy==1.13.1  
  - seaborn==0.13.2
  - pip:
    - scikit-learn==1.5.2
    - librosa==0.10.2.post1
